# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KTYFhpRaa1W32cpEtZ3d3R0qWanNbzcU
"""

from datetime import date
from agences import Agence
from voitures import Voiture

# creation des objets voitures
car1 = Voiture("123 TN 1475", "jeep", date(2000, 10, 01), 3,4)
car2 = Voiture("147 TN 1478", "kia", date(2001, 11, 12), 7,6)
car3 = Voiture("025 TN 1285", "Mercedes", date(2002, 08, 11), 5,5)
car4 = Voiture("698 TN 1204", "bmw", date(2001, 05, 02), 4,2)

# ajouter des voitures dans une liste_voiture
liste_voitures = [voiture1, voiture2, voiture3, voiture4]

# definition de la classe Agence
agence1 = Agence("Agence1", "adresse1", "telephone1", "email1", liste_voitures)

# creation d'une nouvelle voiture pour la recherche
new_car = Voiture("144 TN 1475", "jeep", date(2020, 02, 01))

# Recherche  voiture 
agence1.afficher_voiture(new_car)