# -*- coding: utf-8 -*-
"""VoitureTransformation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cyn4PZJzWHIvN9nlxbJOW1NeToyLrVHv
"""

# definir class transformation
class VoitureTransformation:
    def __init__(self):
        pass
    
    def fit(self):
        pass
    
    def transformer(self):
        pass